### PR TITLE
Lots of improvements

### PR DESCRIPTION
**Pull request by MihajloNesic**
Hi!
I really like this cool mod/utility. I've been using it in my own singleplayer modpack for some time now. I've noticed a few issues while playing, and wanted to fix them myself. I've kept this "version" private, but I've decided to open a PR, since I now feel they would be a great improvement.

Here's a list of what I've changed (or at least what I can remember):
- Improved Heat sources: each source has a 'heatLevel' (starting from 1 and counting up). This heatLevel determines the level required to melt something (from the recipe). I would like this to be configurable and not hard-coded, but I didn't have much time to work on.
- Added some new heat sources (fire, soul fire, soultourch, soul campfire, magma block)
- I've added a 'Creative Heat Source' block. Placing it under the Melter will turn it purple and insta-melt anything (with a valid recipe). This block does not have a default recipe, this is upto a modpack maker to define (if they want).
- JEI shows all the possible heat sources in the recipe viewer for a specific level. It is not perfect, as displaying both blocks, items or fluids was challenging (I would like to refactor this maybe sometime :)). If no valid source is found (eg. level 8 needed, but that level is not defined), a barrier block will be shown with this info. Also, fire and soulfire do not have a texture, so I made a compromise to display flint and steel and a fire charge with appropriate text color and names.
- Melter interaction improvements: Added a way to take out the items form the Melter (not possible before) by right-clicking, added a way to place items into a melter by right-clicking with the item/block.
- Fixed processing time: now the time is actualy correct for the minimum heat level; for each level above minimum, there is a 2 tick bonus so it will melt faster
- Fixed an issue where a different fluid will start melting even though there is already a different fluid present in the Melter
- Default minimum heat level is now 1
- Improved the way items look inside of a Melter. They now lay flat inside. Blocks are the same as before.
- Improved liquid position inside of Melter for small amounts (<200mB). I haven't tested less than 50mB.
- Improved JEI Melter recipe look (centering, added slots, decimal format, etc.)
- Minor improvements, check the commits.

I'll try and post some screenshots below, but I suggest you clone the repo and try the mod for yourself.

I haven't modded in almost 7 years, so this mini-project reminded me of the days I did modding :)
I'm open for any questions and discussion.

All the best.

### CODE REVIEW

**Comment by MihajloNesic** [comment]
Since we can't get fire and soulfire textures from a block (like we use to), these two sources are displayed like so:



Here is the look of lava


Any liquid should work (eg. Superheated Sodium from Mekanism)


If no valid source is present

**Comment by MihajloNesic** [comment]
Heat level 0 (no heat)


Heat level 1


Heat level 2


Heat level 3


Heat level 4


Heat level 5 (Create superheated)


Creative


Creative heat source block (my texture is bad I know)

**Comment by MihajloNesic** [comment]
This is how the item use to render inside of the Melter



This is how it is rendered now

**Comment by MihajloNesic** [comment]
Small amounts of liquid were not visible (inside of the Melter)




They should be visible now (I haven't tested below 50mB but it should be an easy fix if it is still not)

**Comment by MihajloNesic** [comment]
Also, here's the improved JEI look and an info tab for the creative heat source block

**Comment by oierbravo** [comment]
Thanks so much for this PR!!
It looks very promising!

**Comment by MihajloNesic** [comment]
I also had some free time to work on a way to configure heat sources, instead of hard-codding them. I'm having some issues with JEI, but it shouldn't be too difficult to fix. I'll probably add this feature to this PR, since it overhauls the HeatSource.

**Comment by MihajloNesic** [comment]
Configurable heat sources are done.
Resolves #5 

- Heat source list is configured in each save file, under serverconfig.
- Each heat source list entry must be a list of strings, in a pre-defined order. This is really a limitation of the config TOML parser (ref: https://github.com/TheElectronWill/night-config/blob/master/toml/src/main/java/com/electronwill/nightconfig/toml/ValueWriter.java#L35)
- Format of each entry:
  - **type** (`block` or `fluid`) - we need this information mostly because of JEI, because block and fluid type textures are passed to the renderer differently
  - **name** - this is the name (or id) of block/fluid
  - **heat level** (from 1 to 10 only) - the limitation in levels come from the HEAT_SOURCE property in MelterBlock
  - **description** - Any additional info about the heat source. This will be displayed in JEI. Mostly used for blocks with different states.
- Example entry: `["block", "minecraft:dirt", "2", ""]`
- Better check for heat source below melter
- Added 'Melter Heat Sources' in JEI, which shows all valid heat sources and level values
- Changed the way creative melter works. It is not a property of Melter block.
- Few other fixes

**Comment by MihajloNesic** [comment]
These are the default heat sources (same as before). Maybe some sources need tweaking/balancing.
Untitled2




Here's the **description** part of the config. It is displayed in both JEI recipes

**Comment by MihajloNesic** [comment]
Here, I've changed the heat sources to dirt and a fluid from Mekanism mod.
Untitled

It is then reflected in the game.

**Comment by oierbravo** [comment]
Merged! and uploaded new version!!
I still have to add documentation and proper credit to the curseforge, modrinth and README.
Thanks so much!!!!

**Comment by MihajloNesic** [comment]
You're welcome, cheers :)

**Pull request merged**
